### ISSUE TITLE
Delegate support

### ISSUE THREAD

**Issue by breyed** [RickStrahl/wwDotnetBridge#11]
There isn't much guidance about delegates (or callbacks from .NET in general). Async support for blocking .NET calls is clear. But what about non-blocking callbacks, whether as delegates passed as parameters or bound to .NET events? Ideally, they're supported, but if not, it would be good for the documentation to state the limitations definitively.

The wwSmtp example seems to come the closest with a COM-based event. A non-COM-based solution would be preferable, or if not feasible, at least one that supports registration-free COM.

**Comment by RickStrahl** [comment]
It's not supported. Direct callback binding only works through COM - you implement a FoxPro interface to and register that and then .NET can call you back. You have to register your component with COM for that to work.

I don't know of a way to intercept that without the interface mapping.

There's more info on Event handling in the white paper.

**Comment by voxsoftware** [comment]
In my project I have delegate support without COM registration. You are a little inspiration for make my project. Take a look into code, and maybe get an inspiration for implement delegates in your project

https://github.com/voxsoftware/kodnet
