### ISSUE TITLE
GetIndexedProperty docs have wrong argument

### ISSUE THREAD

**Issue by breyed** [RickStrahl/wwDotnetBridge#14]
The docs for [GetIndexedProperty](https://webconnection.west-wind.com/wwClient_docs/_4f00udklk.htm) shows this signature:
```
    o.GetIndexedProperty(loInstance, lcProperty)
```
It looks like `lcProperty` should be `lnIndex`.

**Comment by RickStrahl** [comment]
Fixed in the Web Connection docs, and will be updated in the Client docs next update. Thanks.
