### ISSUE TITLE
instance class

### ISSUE THREAD

**Issue by Frednews** [RickStrahl/wwDotnetBridge#19]
Hello together,

I try to use this wonderful tool since last week. I implemented local with a .net dll and everything Looks fine without Register the dll.
If I initialize the dll on a Server the Assembly Bridge object will create, but when initialize the class with the correct Namespace no object will return and an error.
Then acutal .net 4.6 or 4.7 is installed.

thanks in advanced.

Swen Kleinau

Germany

**Comment by voxsoftware** [comment]
maybe is an issue different .NET version installed, different namespace. Try my project https://github.com/voxsoftware/kodnet
