### ISSUE TITLE
Might be a minor typo "newtosoft" vs "newtonsoft"

### ISSUE THREAD

**Issue by jeffdafoe** [RickStrahl/wwDotnetBridge#20]
https://github.com/RickStrahl/wwDotnetBridge/blob/68ab0ef617f93a4e77506c406f949936cd483dc3/Distribution/wwDotnetBridge.PRG#L186

**Comment by RickStrahl** [comment]
Fixed. Thanks - better late than never 😄 

This usually not a problem - it's the primary assembly that is affected by the zone identifier.
