### ISSUE TITLE
ClrHost.dll build fails because of missing CoreClrHost.dll

### ISSUE THREAD

**Issue by cwollenhaupt** [RickStrahl/wwDotnetBridge#22]
CoreClrHost.cpp is stored at ..\..\..\WebConnection\VisualStudio\C++\smtp\wwsmtp\CoreClrHost.cpp which is outside of the repository structure. The same is true for the CoreClrHost.h file. Building the project results in an 

Error | C1083 | Cannot open source file: '..\..\..\WebConnection\VisualStudio\C++\smtp\wwsmtp\CoreClrHost.cpp': No such file or directory | ClrHost | E:\projects\github.cwollenhaupt.wwDotnetBridge\ClrHost\c1xx | 1 |  

error message.

**Comment by RickStrahl** [comment]
Ah sorry I'll take a look tonight. This was moved over from my Client Tools/Web Connection project so possible there are links to the original folders. 

FWIW, if you're looking at the Core hosting stuff, be aware that this will change. Microsoft has come out with yet another hosting API that is supposed to surplant all the others. It's more complicated and apparently the samples I've tried don't actually work (yet), but the hosting works cross-platform with some minor tweaking (not that this matters for the FoxPro stuff).

There are problems with the current API - namely that you can't safely unload the runtime and a FoxPro RELEASE ALL will clear the references but not allow the AppDomain to be recreated. According to my sources the new API can handle that.

For now this stuff is experimental.

**Comment by cwollenhaupt** [comment]
Thanks for the heads up! I've a modified version of wwDotNetBridge.dll that only subscribes to events that are implemented in the VFP class. Therefore I needed to rebuild the solution. Unloading the ClrHost project fixed this for me. But I'll keep these issues in mind if I start look into Core hosting.

**Comment by cwollenhaupt** [comment]
Thanks, that worked. The only change I had to make was changing the target framework in the Tests project from 4.5 to 4.5.2
