### ISSUE TITLE
StringUtils.cs line 88 small bug

### ISSUE THREAD

**Issue by zdenekkrejci** [RickStrahl/wwDotnetBridge#24]
`  public static string Replicate(string input, int charCount)
        {
            return new StringBuilder().Insert(0, "input", charCount).ToString();
        }`
It should be probably wihtout "input" wihtout qutotation marks here
`            return new StringBuilder().Insert(0, input, charCount).ToString();
`

**Comment by RickStrahl** [comment]
Duh. Thanks. Fixed .

Better late than never :smile:
