### ISSUE TITLE
Problem with DeleteFile function after initializing 

### ISSUE THREAD

**Issue by tpenninckx** [RickStrahl/wwDotnetBridge#25]
Hello,
In the source code, there is a call to :  
DECLARE INTEGER DeleteFile IN WIN32API STRING

This should be Replace by :  
DECLARE INTEGER DeleteFile IN WIN32API AS My_DeleteFile  string

As the Deletefile is an internal function of Foxpro.
Without this renaming, the Foxpro App crash if it calls DeleteFile

Thierry

**Comment by RickStrahl** [comment]
DELETEFILE is not a built-in function
