### ISSUE TITLE
missing file - wwIPStuff.dll

### ISSUE THREAD

**Issue by bernbout** [RickStrahl/wwDotnetBridge#29]
The Readme.md states:
*** Load dependencies and add to Procedure stack
*** Make sure wwDotnetBridge.prg wwDotnetBridge.dll wwIPStuff.dll 
*** are in your FoxPro path

However there is no such file as wwIPStuff.dll nor any link where it can be downloaded in the wwDotnetBridge repositry.
Please add it to the Distribution folder where wwDotnetBridge.dll is located.

**Comment by RickStrahl** [comment]
Use `ClrLoader.dll` instead.

I'll fix the docs.

**Comment by bernbout** [comment]
That was prompt. Thanks Rick. Hope you are well. Cheers.
