### ISSUE TITLE
keeps crashing 

### ISSUE THREAD

**Issue by Moorepheus** [RickStrahl/wwDotnetBridge#4]
trying to use it, but keep getting "unable to load wwDotNetBridge: unable to laod Clr Instance". I copied all 3 of the files needed to the directory in which I am trying to run this.

Thanks

**Comment by RickStrahl** [comment]
No idea. Make sure .NET 4 is installed on your machine or otherwise specify a specific version of the framework you want to load.

**Comment by Moorepheus** [comment]
I have both versions of .Net 2.x & 4.x installed on my device.  Funny thing, and older version (5.64.0.0) works like a charm.

This is where it’s crashing  DECLARE Integer ClrCreateInstanceFrom IN WWC_CLR_HOSTDLL string, string, string@, integer@ of the LOAD() function in the wwDotNetBridge.prg and it doesn’t matter if I pass in what .Net version to use or not.

Thanks
————————————————
Mark C. Moore
Software Engineer

NTS Data Services, LLC
2079 Sawyer Rd
Niagara Falls, NY 14304

Phone: 800-458-3820 ext 303
Fax: 800-598-1478
Mark.Moore@ntsdata.com<mailto:Mark.Moore@ntsdata.com>
www.NTSDATA.com
P Save a tree. Don't print this e-mail, unless  it is truly necessary.
Confidentiality Notice:
This fax/e-mail transmission, with accompanying records, is intended only for the use of the individual or entity to which it is addressed and may contain confidential and/or privileged information belonging to the sender, including individually identifiable health information subject to the privacy and security provisions of HIPAA. This information may be protected by pertinent privilege(s), e.g., attorney-client, doctor-patient, HIPAA etc., which will be enforced to the fullest extent of the law. If you are not the intended recipient, you are hereby notified that any examination, analysis, disclosure, copying, dissemination, distribution, sharing, or use of the information in this transmission is strictly prohibited. If you have received this message and associated documents in error, please notify the sender immediately for instructions. If this message was received by e-mail, please delete the original message.

**Comment by Moorepheus** [comment]
Ok, after looking at all your releases and only using the files in the 'DISTRUBTION' directory of the ZIP, I found that V5.68, V5.72 & V6 works, however, the MASTER and V5.67 do not.

Btw, thanks for this great work.

**Comment by RickStrahl** [comment]
Not sure what you're saying. The distribution folder for the zip comes from the master branch. Either one should work.
