### ISSUE TITLE
VS 2015 Windows 10 - can not instantiate wwDotNetBridge from VFP

### ISSUE THREAD

**Issue by NaomiN** [RickStrahl/wwDotnetBridge#5]
I am getting - 1 for these lines of code

DECLARE Integer ClrCreateInstanceFrom IN WWC_CLR_HOSTDLL string, string, string@, integer@

		lcError = SPACE(2048)
		lnSize = 0
		lnDispHandle = ClrCreateInstanceFrom(FULLPATH("wwDotNetBridge.dll"),;
				"Westwind.WebConnection.wwDotNetBridge",@lcError,@lnSize)

		IF lnDispHandle < 1
		   this.SetError( "Unable to load Clr Instance. " + LEFT(lcError,lnSize) )
		   RETURN NULL 
		ENDIF

What can I do?

**Comment by vicosx12** [comment]
wwDotNetBridge issue with .NET Framework 4.6.2 (Windows 10 Anniversary Update: 394802). Always return v.2.0.50727.8745.

*** Load dependencies
DO wwDotnetBridge

** Create an instance
loBridge = GetwwDotnetBridge("V4")
? loBridge.GetDotnetversion()

loBridge = CreateObject("wwDotNetBridge", "V4")
? loBridge.GetDotnetversion()

**Comment by RickStrahl** [comment]
Make sure you use the files from the distribution folder.

**Comment by vicosx12** [comment]
My mistake. Loading eTecnologiaNetExtender in _STARTUP.

**Comment by RickStrahl** [comment]
Yeah if something else loads the .NET Runtime you can't change it subsequently. Only one runtime can run in a Process.

**Comment by vicosx12** [comment]
Thanks.
